language: python

python:
  - '3.5'
  - '3.6'

before_install:
  - sudo apt install python3-pip

install:
  - sudo pip3 install -r requirements.txt --use-mirrors

script: python3 -m unittest tests/tests.py
