language: python
dist: trusty

addons:
  apt:
    packages:
      - 'python3'
      - 'python3-pip'

python:
  - 3.5
  - 3.6

before_install:
  - sudo apt-get update

install:
  - pip3 install -r requirements.txt

script: 
  - if [[$TRAVIS_PYTHON_VERSION == '3.5' || $TRAVIS_PYTHON_VERSION == '3.6']]; then python3 -m unittest tests/tests.py; fi
