[package]
name = "le-chiffre"
version = "0.1.0"
authors = ["arturovt <arthurandrosovich@gmail.com>"]

[dependencies]
rand = "0.3.18"
rpassword = "1.0.0"
rust-crypto = "0.2.36"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
clipboard = "0.4.2"
